// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// JetstreamPlanBackfill_BlockRange is a "blockRange" in the network.bsky.jetstream.planBackfill schema.
type JetstreamPlanBackfill_BlockRange struct {
	LexiconTypeID string `json:"$type,omitempty"`
	First         int64  `json:"first"` // First block index in this inclusive range.
	Last          int64  `json:"last"`  // Last block index in this inclusive range.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_BlockRange.
var (
	cborKey_JetstreamPlanBackfill_BlockRange_last        = cbor.AppendTextKey(nil, "last")
	cborKey_JetstreamPlanBackfill_BlockRange_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanBackfill_BlockRange_first       = cbor.AppendTextKey(nil, "first")
)

func (s *JetstreamPlanBackfill_BlockRange) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_BlockRange) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "last", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_last...)
		buf = cbor.AppendInt(buf, s.Last)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "first", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_first...)
		buf = cbor.AppendInt(buf, s.First)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_last...)
		buf = cbor.AppendInt(buf, s.Last)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_BlockRange_first...)
		buf = cbor.AppendInt(buf, s.First)
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_BlockRange) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_BlockRange) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "last" {
				s.Last, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "first" {
				s.First, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanBackfill_BlockRange.
var (
	jsonKey_JetstreamPlanBackfill_BlockRange_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_BlockRange_first       = []byte("\"first\":")
	jsonKey_JetstreamPlanBackfill_BlockRange_last        = []byte("\"last\":")
)

func (s *JetstreamPlanBackfill_BlockRange) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_BlockRange) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_BlockRange_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_BlockRange_first...)
	buf = cbor.AppendJSONInt(buf, s.First)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_BlockRange_last...)
	buf = cbor.AppendJSONInt(buf, s.Last)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_BlockRange) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_BlockRange) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "first":
			s.First, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "last":
			s.Last, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamPlanBackfill_DidTombstone is a "didTombstone" in the network.bsky.jetstream.planBackfill schema.
type JetstreamPlanBackfill_DidTombstone struct {
	LexiconTypeID string `json:"$type,omitempty"`
	DID           string `json:"did"` // The account whose DID-level tombstone (account-delete or sync) this is.
	Seq           int64  `json:"seq"` // The jetstream seq of the highest account-delete/sync for this DID within the snapshot range. The ...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_DidTombstone.
var (
	cborKey_JetstreamPlanBackfill_DidTombstone_did         = cbor.AppendTextKey(nil, "did")
	cborKey_JetstreamPlanBackfill_DidTombstone_seq         = cbor.AppendTextKey(nil, "seq")
	cborKey_JetstreamPlanBackfill_DidTombstone_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *JetstreamPlanBackfill_DidTombstone) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_DidTombstone) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "seq", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_DidTombstone_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_DidTombstone) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_DidTombstone) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "seq" {
				s.Seq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanBackfill_DidTombstone.
var (
	jsonKey_JetstreamPlanBackfill_DidTombstone_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_DidTombstone_did         = []byte("\"did\":")
	jsonKey_JetstreamPlanBackfill_DidTombstone_seq         = []byte("\"seq\":")
)

func (s *JetstreamPlanBackfill_DidTombstone) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_DidTombstone) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_DidTombstone_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_DidTombstone_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_DidTombstone_seq...)
	buf = cbor.AppendJSONInt(buf, s.Seq)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_DidTombstone) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_DidTombstone) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "seq":
			s.Seq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Error name constants for JetstreamPlanBackfill.
const (
	ErrJetstreamPlanBackfill_PlanTooLarge = "PlanTooLarge" // The plan would exceed the server's configured response/work entry limit.
)

// Precomputed JSON key tokens for JetstreamPlanBackfill_Output.
var (
	jsonKey_JetstreamPlanBackfill_Output_dollar_type           = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_Output_didTombstones         = []byte("\"didTombstones\":")
	jsonKey_JetstreamPlanBackfill_Output_didTombstonesIncluded = []byte("\"didTombstonesIncluded\":")
	jsonKey_JetstreamPlanBackfill_Output_plannedThroughSeq     = []byte("\"plannedThroughSeq\":")
	jsonKey_JetstreamPlanBackfill_Output_segments              = []byte("\"segments\":")
	jsonKey_JetstreamPlanBackfill_Output_stats                 = []byte("\"stats\":")
)

func (s *JetstreamPlanBackfill_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if len(s.DidTombstones) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_didTombstones...)
		buf = append(buf, '[')
		for i, item := range s.DidTombstones {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if s.DidTombstonesIncluded.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_didTombstonesIncluded...)
		buf = cbor.AppendJSONBool(buf, s.DidTombstonesIncluded.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_plannedThroughSeq...)
	buf = cbor.AppendJSONInt(buf, s.PlannedThroughSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_segments...)
	buf = append(buf, '[')
	for i, item := range s.Segments {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Output_stats...)
	{
		var err error
		buf, err = s.Stats.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "didTombstones":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.DidTombstones = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamPlanBackfill_DidTombstone
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.DidTombstones = append(s.DidTombstones, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "didTombstonesIncluded":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v bool
				v, pos, err = cbor.ReadJSONBool(data, pos)
				if err != nil {
					return 0, err
				}
				s.DidTombstonesIncluded = gt.Some(v)
			}
		case "plannedThroughSeq":
			s.PlannedThroughSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segments":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Segments = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamPlanBackfill_Segment
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Segments = append(s.Segments, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "stats":
			pos, err = s.Stats.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_Output.
var (
	cborKey_JetstreamPlanBackfill_Output_dollar_type           = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanBackfill_Output_stats                 = cbor.AppendTextKey(nil, "stats")
	cborKey_JetstreamPlanBackfill_Output_segments              = cbor.AppendTextKey(nil, "segments")
	cborKey_JetstreamPlanBackfill_Output_didTombstones         = cbor.AppendTextKey(nil, "didTombstones")
	cborKey_JetstreamPlanBackfill_Output_plannedThroughSeq     = cbor.AppendTextKey(nil, "plannedThroughSeq")
	cborKey_JetstreamPlanBackfill_Output_didTombstonesIncluded = cbor.AppendTextKey(nil, "didTombstonesIncluded")
)

func (s *JetstreamPlanBackfill_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if len(s.DidTombstones) > 0 {
		n++
	}
	if s.DidTombstonesIncluded.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "stats", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_stats...)
		{
			var err error
			buf, err = s.Stats.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segments", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "didTombstones", buf)
		if len(s.DidTombstones) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_didTombstones...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.DidTombstones)))
			for _, item := range s.DidTombstones {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "plannedThroughSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_plannedThroughSeq...)
		buf = cbor.AppendInt(buf, s.PlannedThroughSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "didTombstonesIncluded", buf)
		if s.DidTombstonesIncluded.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_didTombstonesIncluded...)
			buf = cbor.AppendBool(buf, s.DidTombstonesIncluded.Val())
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_stats...)
		{
			var err error
			buf, err = s.Stats.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		if len(s.DidTombstones) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_didTombstones...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.DidTombstones)))
			for _, item := range s.DidTombstones {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Output_plannedThroughSeq...)
		buf = cbor.AppendInt(buf, s.PlannedThroughSeq)
		if s.DidTombstonesIncluded.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Output_didTombstonesIncluded...)
			buf = cbor.AppendBool(buf, s.DidTombstonesIncluded.Val())
		}
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "stats" {
				pos, err = s.Stats.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "segments" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Segments = make([]JetstreamPlanBackfill_Segment, arrLen)
					for idx := range arrLen {
						pos, err = s.Segments[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 13:
			if string(data[keyStart:keyEnd]) == "didTombstones" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.DidTombstones = make([]JetstreamPlanBackfill_DidTombstone, arrLen)
					for idx := range arrLen {
						pos, err = s.DidTombstones[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 17:
			if string(data[keyStart:keyEnd]) == "plannedThroughSeq" {
				s.PlannedThroughSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 21:
			if string(data[keyStart:keyEnd]) == "didTombstonesIncluded" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v bool
					v, pos, err = cbor.ReadBool(data, pos)
					if err != nil {
						return 0, err
					}
					s.DidTombstonesIncluded = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamPlanBackfill_Output struct {
	LexiconTypeID         string                               `json:"$type,omitempty"`
	DidTombstones         []JetstreamPlanBackfill_DidTombstone `json:"didTombstones,omitempty"`        // DID-level tombstones (account-delete / sync) with seq in (afterSeq, plannedThroughSeq], intersect...
	DidTombstonesIncluded gt.Option[bool]                      `json:"didTombstonesIncluded,omitzero"` // True iff this response carries the DID-tombstone snapshot (i.e. wantDidTombstones was set on the ...
	PlannedThroughSeq     int64                                `json:"plannedThroughSeq"`              // Highest sealed seq covered by this plan, capped by beforeSeq when provided.
	Segments              []JetstreamPlanBackfill_Segment      `json:"segments"`
	Stats                 JetstreamPlanBackfill_Stats          `json:"stats"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed JSON key tokens for JetstreamPlanBackfill_Input.
var (
	jsonKey_JetstreamPlanBackfill_Input_dollar_type       = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_Input_afterSeq          = []byte("\"afterSeq\":")
	jsonKey_JetstreamPlanBackfill_Input_beforeSeq         = []byte("\"beforeSeq\":")
	jsonKey_JetstreamPlanBackfill_Input_collections       = []byte("\"collections\":")
	jsonKey_JetstreamPlanBackfill_Input_dids              = []byte("\"dids\":")
	jsonKey_JetstreamPlanBackfill_Input_wantDidTombstones = []byte("\"wantDidTombstones\":")
)

func (s *JetstreamPlanBackfill_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.AfterSeq.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_afterSeq...)
		buf = cbor.AppendJSONInt(buf, s.AfterSeq.Val())
		first = false
	}
	if s.BeforeSeq.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_beforeSeq...)
		buf = cbor.AppendJSONInt(buf, s.BeforeSeq.Val())
		first = false
	}
	if len(s.Collections) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_collections...)
		buf = append(buf, '[')
		for i, item := range s.Collections {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.Dids) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_dids...)
		buf = append(buf, '[')
		for i, item := range s.Dids {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if s.WantDidTombstones.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Input_wantDidTombstones...)
		buf = cbor.AppendJSONBool(buf, s.WantDidTombstones.Val())
		first = false
	}
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "afterSeq":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.AfterSeq = gt.Some(v)
			}
		case "beforeSeq":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.BeforeSeq = gt.Some(v)
			}
		case "collections":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Collections = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Collections = append(s.Collections, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "dids":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Dids = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Dids = append(s.Dids, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "wantDidTombstones":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v bool
				v, pos, err = cbor.ReadJSONBool(data, pos)
				if err != nil {
					return 0, err
				}
				s.WantDidTombstones = gt.Some(v)
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_Input.
var (
	cborKey_JetstreamPlanBackfill_Input_dids              = cbor.AppendTextKey(nil, "dids")
	cborKey_JetstreamPlanBackfill_Input_dollar_type       = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanBackfill_Input_afterSeq          = cbor.AppendTextKey(nil, "afterSeq")
	cborKey_JetstreamPlanBackfill_Input_beforeSeq         = cbor.AppendTextKey(nil, "beforeSeq")
	cborKey_JetstreamPlanBackfill_Input_collections       = cbor.AppendTextKey(nil, "collections")
	cborKey_JetstreamPlanBackfill_Input_wantDidTombstones = cbor.AppendTextKey(nil, "wantDidTombstones")
)

func (s *JetstreamPlanBackfill_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 0 + countExtra(s.extra, extraEncodingCBOR)
	if len(s.Dids) > 0 {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	if s.AfterSeq.HasVal() {
		n++
	}
	if s.BeforeSeq.HasVal() {
		n++
	}
	if len(s.Collections) > 0 {
		n++
	}
	if s.WantDidTombstones.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "dids", buf)
		if len(s.Dids) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_dids...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Dids)))
			for _, item := range s.Dids {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "afterSeq", buf)
		if s.AfterSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_afterSeq...)
			buf = cbor.AppendInt(buf, s.AfterSeq.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "beforeSeq", buf)
		if s.BeforeSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_beforeSeq...)
			buf = cbor.AppendInt(buf, s.BeforeSeq.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "collections", buf)
		if len(s.Collections) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_collections...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Collections)))
			for _, item := range s.Collections {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "wantDidTombstones", buf)
		if s.WantDidTombstones.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_wantDidTombstones...)
			buf = cbor.AppendBool(buf, s.WantDidTombstones.Val())
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if len(s.Dids) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_dids...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Dids)))
			for _, item := range s.Dids {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.AfterSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_afterSeq...)
			buf = cbor.AppendInt(buf, s.AfterSeq.Val())
		}
		if s.BeforeSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_beforeSeq...)
			buf = cbor.AppendInt(buf, s.BeforeSeq.Val())
		}
		if len(s.Collections) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_collections...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Collections)))
			for _, item := range s.Collections {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.WantDidTombstones.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Input_wantDidTombstones...)
			buf = cbor.AppendBool(buf, s.WantDidTombstones.Val())
		}
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "dids" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Dids = make([]string, arrLen)
					for idx := range arrLen {
						s.Dids[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "afterSeq" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.AfterSeq = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "beforeSeq" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.BeforeSeq = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "collections" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Collections = make([]string, arrLen)
					for idx := range arrLen {
						s.Collections[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 17:
			if string(data[keyStart:keyEnd]) == "wantDidTombstones" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v bool
					v, pos, err = cbor.ReadBool(data, pos)
					if err != nil {
						return 0, err
					}
					s.WantDidTombstones = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamPlanBackfill_Input struct {
	LexiconTypeID     string           `json:"$type,omitempty"`
	AfterSeq          gt.Option[int64] `json:"afterSeq,omitzero"`          // Lower exclusive sequence bound. Rows with seq <= afterSeq are outside the requested window.
	BeforeSeq         gt.Option[int64] `json:"beforeSeq,omitzero"`         // Upper inclusive sequence bound. Rows with seq > beforeSeq are outside the requested window.
	Collections       []string         `json:"collections,omitempty"`      // Collection filters to match. Each entry is either an exact NSID (e.g. app.bsky.feed.post) or a na...
	Dids              []string         `json:"dids,omitempty"`             // Exact DIDs to match. Missing or empty means all DIDs.
	WantDidTombstones gt.Option[bool]  `json:"wantDidTombstones,omitzero"` // Set true ONLY on the first page of a fresh backfill to request the DID-level tombstone snapshot o...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// JetstreamPlanBackfill calls the XRPC procedure "network.bsky.jetstream.planBackfill".
//
// Plan sealed-archive downloads for a historical backfill. The response names whole sealed segments or sealed-segment block ranges that may contain rows matching the requested exact DID and collection filters. This is a transport planner only: clients must still decode rows, apply exact filtering, and coordinate live-tail subscription independently. On the first page (wantDidTombstones), the response also carries a DID-level tombstone snapshot so a collection-filtered backfill can suppress records of accounts deleted within the planned range.
func JetstreamPlanBackfill(ctx context.Context, c *xrpc.Client, input *JetstreamPlanBackfill_Input) (*JetstreamPlanBackfill_Output, error) {
	var out JetstreamPlanBackfill_Output
	return &out, c.Procedure(ctx, "network.bsky.jetstream.planBackfill", input, &out)
}

// JetstreamPlanBackfill_Segment is a "segment" in the network.bsky.jetstream.planBackfill schema.
type JetstreamPlanBackfill_Segment struct {
	LexiconTypeID string                             `json:"$type,omitempty"`
	Blocks        []JetstreamPlanBackfill_BlockRange `json:"blocks,omitempty"` // Inclusive block ranges. Present only when mode is blocks.
	Checksum      string                             `json:"checksum"`         // Segment-format xxh3 metadata checksum as 16-char hex.
	Index         int64                              `json:"index"`            // Zero-based segment index.
	MaxSeq        int64                              `json:"maxSeq"`
	MinSeq        int64                              `json:"minSeq"`
	Mode          string                             `json:"mode"` // segment means download the whole segment with getSegment; blocks means download the listed block ...
	Name          string                             `json:"name"` // Segment filename accepted by getSegment and getBlock.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_Segment.
var (
	cborKey_JetstreamPlanBackfill_Segment_mode        = cbor.AppendTextKey(nil, "mode")
	cborKey_JetstreamPlanBackfill_Segment_name        = cbor.AppendTextKey(nil, "name")
	cborKey_JetstreamPlanBackfill_Segment_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanBackfill_Segment_index       = cbor.AppendTextKey(nil, "index")
	cborKey_JetstreamPlanBackfill_Segment_blocks      = cbor.AppendTextKey(nil, "blocks")
	cborKey_JetstreamPlanBackfill_Segment_maxSeq      = cbor.AppendTextKey(nil, "maxSeq")
	cborKey_JetstreamPlanBackfill_Segment_minSeq      = cbor.AppendTextKey(nil, "minSeq")
	cborKey_JetstreamPlanBackfill_Segment_checksum    = cbor.AppendTextKey(nil, "checksum")
)

func (s *JetstreamPlanBackfill_Segment) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Segment) AppendCBOR(buf []byte) ([]byte, error) {
	n := 6 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if len(s.Blocks) > 0 {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "mode", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_mode...)
		buf = cbor.AppendText(buf, s.Mode)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "name", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "index", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "blocks", buf)
		if len(s.Blocks) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_blocks...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Blocks)))
			for _, item := range s.Blocks {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "maxSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "minSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "checksum", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_mode...)
		buf = cbor.AppendText(buf, s.Mode)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		if len(s.Blocks) > 0 {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_blocks...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Blocks)))
			for _, item := range s.Blocks {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_Segment) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Segment) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "mode" {
				s.Mode, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "index" {
				s.Index, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "blocks" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Blocks = make([]JetstreamPlanBackfill_BlockRange, arrLen)
					for idx := range arrLen {
						pos, err = s.Blocks[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "maxSeq" {
				s.MaxSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "minSeq" {
				s.MinSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "checksum" {
				s.Checksum, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanBackfill_Segment.
var (
	jsonKey_JetstreamPlanBackfill_Segment_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_Segment_blocks      = []byte("\"blocks\":")
	jsonKey_JetstreamPlanBackfill_Segment_checksum    = []byte("\"checksum\":")
	jsonKey_JetstreamPlanBackfill_Segment_index       = []byte("\"index\":")
	jsonKey_JetstreamPlanBackfill_Segment_maxSeq      = []byte("\"maxSeq\":")
	jsonKey_JetstreamPlanBackfill_Segment_minSeq      = []byte("\"minSeq\":")
	jsonKey_JetstreamPlanBackfill_Segment_mode        = []byte("\"mode\":")
	jsonKey_JetstreamPlanBackfill_Segment_name        = []byte("\"name\":")
)

func (s *JetstreamPlanBackfill_Segment) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Segment) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if len(s.Blocks) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_blocks...)
		buf = append(buf, '[')
		for i, item := range s.Blocks {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_checksum...)
	buf = cbor.AppendJSONString(buf, s.Checksum)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_index...)
	buf = cbor.AppendJSONInt(buf, s.Index)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_maxSeq...)
	buf = cbor.AppendJSONInt(buf, s.MaxSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_minSeq...)
	buf = cbor.AppendJSONInt(buf, s.MinSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_mode...)
	buf = cbor.AppendJSONString(buf, s.Mode)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Segment_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_Segment) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Segment) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "blocks":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Blocks = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamPlanBackfill_BlockRange
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Blocks = append(s.Blocks, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "checksum":
			s.Checksum, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "index":
			s.Index, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "maxSeq":
			s.MaxSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "minSeq":
			s.MinSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "mode":
			s.Mode, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamPlanBackfill_Stats is a "stats" in the network.bsky.jetstream.planBackfill schema.
type JetstreamPlanBackfill_Stats struct {
	LexiconTypeID    string `json:"$type,omitempty"`
	BlocksMatched    int64  `json:"blocksMatched"`
	Entries          int64  `json:"entries"` // Number of response work entries counted against the server plan limit.
	SegmentsExamined int64  `json:"segmentsExamined"`
	SegmentsMatched  int64  `json:"segmentsMatched"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanBackfill_Stats.
var (
	cborKey_JetstreamPlanBackfill_Stats_dollar_type      = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanBackfill_Stats_entries          = cbor.AppendTextKey(nil, "entries")
	cborKey_JetstreamPlanBackfill_Stats_blocksMatched    = cbor.AppendTextKey(nil, "blocksMatched")
	cborKey_JetstreamPlanBackfill_Stats_segmentsMatched  = cbor.AppendTextKey(nil, "segmentsMatched")
	cborKey_JetstreamPlanBackfill_Stats_segmentsExamined = cbor.AppendTextKey(nil, "segmentsExamined")
)

func (s *JetstreamPlanBackfill_Stats) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Stats) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "entries", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_entries...)
		buf = cbor.AppendInt(buf, s.Entries)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "blocksMatched", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_blocksMatched...)
		buf = cbor.AppendInt(buf, s.BlocksMatched)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsMatched", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_segmentsMatched...)
		buf = cbor.AppendInt(buf, s.SegmentsMatched)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsExamined", buf)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_segmentsExamined...)
		buf = cbor.AppendInt(buf, s.SegmentsExamined)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_entries...)
		buf = cbor.AppendInt(buf, s.Entries)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_blocksMatched...)
		buf = cbor.AppendInt(buf, s.BlocksMatched)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_segmentsMatched...)
		buf = cbor.AppendInt(buf, s.SegmentsMatched)
		buf = append(buf, cborKey_JetstreamPlanBackfill_Stats_segmentsExamined...)
		buf = cbor.AppendInt(buf, s.SegmentsExamined)
	}
	return buf, nil
}

func (s *JetstreamPlanBackfill_Stats) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Stats) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "entries" {
				s.Entries, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 13:
			if string(data[keyStart:keyEnd]) == "blocksMatched" {
				s.BlocksMatched, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 15:
			if string(data[keyStart:keyEnd]) == "segmentsMatched" {
				s.SegmentsMatched, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 16:
			if string(data[keyStart:keyEnd]) == "segmentsExamined" {
				s.SegmentsExamined, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanBackfill_Stats.
var (
	jsonKey_JetstreamPlanBackfill_Stats_dollar_type      = []byte("\"$type\":")
	jsonKey_JetstreamPlanBackfill_Stats_blocksMatched    = []byte("\"blocksMatched\":")
	jsonKey_JetstreamPlanBackfill_Stats_entries          = []byte("\"entries\":")
	jsonKey_JetstreamPlanBackfill_Stats_segmentsExamined = []byte("\"segmentsExamined\":")
	jsonKey_JetstreamPlanBackfill_Stats_segmentsMatched  = []byte("\"segmentsMatched\":")
)

func (s *JetstreamPlanBackfill_Stats) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanBackfill_Stats) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanBackfill_Stats_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Stats_blocksMatched...)
	buf = cbor.AppendJSONInt(buf, s.BlocksMatched)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Stats_entries...)
	buf = cbor.AppendJSONInt(buf, s.Entries)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Stats_segmentsExamined...)
	buf = cbor.AppendJSONInt(buf, s.SegmentsExamined)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanBackfill_Stats_segmentsMatched...)
	buf = cbor.AppendJSONInt(buf, s.SegmentsMatched)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanBackfill_Stats) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanBackfill_Stats) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "blocksMatched":
			s.BlocksMatched, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "entries":
			s.Entries, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segmentsExamined":
			s.SegmentsExamined, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segmentsMatched":
			s.SegmentsMatched, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
