// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for JetstreamGetBlock.
const (
	ErrJetstreamGetBlock_SegmentNotFound = "SegmentNotFound" // No sealed segment exists for the given name.
	ErrJetstreamGetBlock_BlockNotFound   = "BlockNotFound"   // blockIndex is >= the segment's block_count.
)

// JetstreamGetBlock calls the XRPC query "network.bsky.jetstream.getBlock".
//
// Download a single sealed-segment block by index. Returns the raw zstd-compressed block frame exactly as stored on disk (no 8-byte length prefix; Content-Length carries the length). The response is immutable for a given ETag and is CDN-cacheable. Clients fetch the blocks named by a query plan and decode each frame with the standard block decoder.
func JetstreamGetBlock(ctx context.Context, c *xrpc.Client, blockIndex int64, segment string) ([]byte, error) {
	params := map[string]any{}
	params["blockIndex"] = blockIndex
	params["segment"] = segment
	return c.QueryRaw(ctx, "network.bsky.jetstream.getBlock", params)
}
